### ISSUE TITLE
Logout when a person is unauthorised

### ISSUE THREAD

**Issue by dbollaer** [simplesamlphp/simplesamlphp-module-authorize#17]
We use entraID as our authentication source. Some users have multiple accounts and can login with a guest account, instead of their member accounts.
It happens that people misclick and select the wrong account.
Now people are stuck, because they can not logout.
So they would need to close there browsers and try again.

Ideally I would allow people to logout and redirect them to a logout page, telling them close your browser and try again.

I could also after logout, try to redirect them back to the Service Provider. But I think this approach will be to complicated and might cause side effects.

I don't mind implementing this feature myself.
If you could give me some advice, I ll try to tackle the problem next week.
Thank you in advance.

**Comment by thijskh** [comment]
Hi Danny, the most straightforward change would be to allow to configure some kind of "continue" URL that would be used instead of the logout button when defined. This is simple and seems generically useful. Whatever you redirect to can be informational, or perform some logout or other.

A different more complex approach is to provide not a logout button but a 'relogin' button that would restart the login but with ForceAuthn=true set. I'm not sure what it would entail to make this, but it could solve this specific problem.

**Comment by tvdijen** [comment]
I was thinking about ForceAuthn too, because basically what you want is to logout from the Entra IdP and re-authenticate using a different user.. Unfortunately we cannot control the session at the IdP, but we _can_ enforce re-authentication using this flag.

I think it's really not that complex to do this:
- Redirect the user to a new endpoint (i.e. /reauthenticate)
- On that new endpoint, get the current state and find the current authsource (I think the array key is called AuthId)
- Create a new instance of \SimpleSAML\Auth\Simple passing the AuthId as parameter
- Call login() on the newly created object and pass 'ForceAuthn' => true as parameter.

**Comment by dbollaer** [comment]
@thijskh and @tvdijen thank your help. I am planning to submit this when I am done. I think a feature flag is required for this new behaviour for not to break backward compatibility. What do you think about allowReAuthenticateOnUnauthorized?
I am open for suggestions.

**Comment by tvdijen** [comment]
I think a feature-flag is overkill in this case, but if you must, I suggest keeping it short: `allowReauthentication` should suffice if the flag is properly described in a comment.
